# Site Details
site_name: fHDHR Docs
site_description: The official guide for fHDHR
site_author: deathbybandaid
site_url: https://fhdhr.github.io/fHDHR_Docs/
edit_uri: https://github.com/fhdhr/fHDHR_Docs/edit/development/docs/
repo_url: https://github.com/fhdhr/fHDHR_Docs
repo_name: fhdhr/fHDHR_Docs

# Site appearance (logos, colours, icons)
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - navigation.tabs
    - navigation.instant
  favicon: images/logo.ico
  logo: images/logo.ico
  palette:
    scheme: preference
  
# Markdown extensions
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4
  - abbr

# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false

# Navigation Layout
nav:
  - Home: index.md
  #- Installation: 
    #- Linux: installation_linux.md
    #- Docker: installation_docker.md
    #- Windows: installation_windows.md
  - Config: 
    - Basic Config: config.md
    - Advanced Config: adv_config.md
    - Docker: installation_docker.md
  - Plugins: plugins.md
  - WebUI: webui.md
  - Usage: usage.md
  - Related Projects: related_projects.md
