# Site Details
site_name: fHDHR Docs
site_description: The official guide for fHDHR
site_author: deathbybandaid
site_url: https://fhdhr.github.io/fHDHR_Docs/
edit_uri: https://github.com/fhdhr/fHDHR_Docs/edit/development/docs/
repo_url: https://github.com/fhdhr/fHDHR_Docs
repo_name: fhdhr/fHDHR_Docs

# Site appearance (logos, colours, icons)
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  favicon: images/logo.ico
  logo: images/logo.ico
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
# Markdown extensions
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 4


# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false

# Navigation Layout
nav:
  - Home: index.md
  #- Installation: 
    #- Linux: installation_linux.md
    #- Docker: installation_docker.md
    #- Windows: installation_windows.md
  - Config: 
    - Basic Config: config.md
    - Advanced Config: adv_config.md
    - Docker: installation_docker.md
  - Plugins: plugins.md
  - WebUI: webui.md
  - Usage: usage.md
  - Getting Involved:
    - Submitting to the docs: submitting_docs.md
